# -*- coding: utf-8 -*-
"""CIS412 - Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X4DTTs8qbwI3FR-AMNUcAsSfd_mJkscz
"""

import pandas as pd

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

train.head()
test.head()

train = train.iloc[:, 1:]
test = test.iloc[:, 1:]

train.head()

#Train Test Split

train_X = train.iloc[:, :-1]
train_y = train.iloc[:, -1]

test_X = test.iloc[:, :-1]
test_y = test.iloc[:, -1]

#Encode Feature Matrix

import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Identify categorical columns
cat_cols = ['Gender', 'Customer Type', 'Type of Travel', 'Class']

# Create a OneHotEncoder instance
one_hot_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Create a ColumnTransformer to apply OneHotEncoder to categorical columns
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', one_hot_encoder, cat_cols)
    ],
    remainder='passthrough' # Keep other columns as they are
)

# Fit and transform train_X
train_X_encoded = preprocessor.fit_transform(train_X)

# Transform test_X
test_X_encoded = preprocessor.transform(test_X)

# Get feature names after one-hot encoding
encoded_feature_names = preprocessor.named_transformers_['cat'].get_feature_names_out(cat_cols)
other_features = [col for col in train_X.columns if col not in cat_cols] # Corrected 'cat' to 'cat_cols'
all_feature_names = list(encoded_feature_names) + list(other_features)

# Convert the encoded arrays back to DataFrames with proper column names
train_X = pd.DataFrame(train_X_encoded, columns=all_feature_names, index=train_X.index)
test_X = pd.DataFrame(test_X_encoded, columns=all_feature_names, index=test_X.index)

print("Encoded train_X head:")
print(train_X.head())
print("\nEncoded test_X head:")
print(test_X.head())

#Encode target vector

train_y = train_y.map({'satisfied': 1, 'neutral or dissatisfied': 0})
test_y = test_y.map({'satisfied': 1, 'neutral or dissatisfied': 0})

test_y.head()

# Create Decision Tree Classifier Model

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(criterion="entropy", random_state=0)

dt.fit(train_X, train_y)

dt.score(train_X, train_y)

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

disp_train = ConfusionMatrixDisplay.from_estimator(dt, train_X, train_y)

plt.title("Confusion Matrix - Training Set")
plt.show()

#Predict on test set
y_pred = dt.predict(test_X)


from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score
print("Test Set Perfomance Metrics")
print("Accuracy:", accuracy_score(test_y, y_pred))
print("Precision:", precision_score(test_y, y_pred))
print("Recall:", recall_score(test_y, y_pred))
print("F1:", f1_score(test_y, y_pred))


# Generate and plot confusion matrix for the test set
disp_test = ConfusionMatrixDisplay.from_estimator(dt, test_X, test_y)

# Plot the confusion matrix
plt.title("Confusion Matrix - Test Set")
plt.show()

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

# Get predicted probabilities (NOT class predictions)
y_prob = dt.predict_proba(test_X)[:, 1]

# Compute ROC curve
fpr, tpr, thresholds = roc_curve(test_y, y_prob)

# Compute AUC
auc_score = roc_auc_score(test_y, y_prob)

# Plot
plt.figure()
plt.plot(fpr, tpr, label=f"AUC = {auc_score:.3f}")
plt.plot([0, 1], [0, 1], linestyle='--')  # random classifier line

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Range of max_depth values to test
max_depth_range = range(1, 11)

# Lists to store the training and test accuracies for each max_depth
train_accuracies = []
test_accuracies = []

# Iterate through max_depth values
for depth in max_depth_range:
    clf = DecisionTreeClassifier(max_depth=depth, random_state=0, criterion= "entropy")
    # Train the model on the training data
    clf.fit(train_X, train_y)

    # Evaluate the model on the training data
    train_accuracy = clf.score(train_X, train_y)
    train_accuracies.append(train_accuracy)

    # Evaluate the model on the test data
    test_accuracy = clf.score(test_X, test_y)
    test_accuracies.append(test_accuracy)

    print(f"Max Depth: {depth}, Training Accuracy: {train_accuracy:.3f}, Test Accuracy: {test_accuracy:.3f}")

# Plot the training and test accuracies vs max_depth
plt.figure(figsize=(10, 6))
plt.plot(max_depth_range, train_accuracies, marker='o', label="Training Accuracy")
plt.plot(max_depth_range, test_accuracies, marker='o', label="Test Accuracy")
plt.title('Training and Test Accuracy vs Max Depth')
plt.xlabel('Max Depth')
plt.ylabel('Accuracy')
plt.xticks(max_depth_range)
plt.legend()
plt.grid(True)
plt.show()

"""Choose max_depth = 7 to prevent overfitting (optimize complexity)"""

tree_pruned = DecisionTreeClassifier(max_depth=7, random_state=0, criterion= "entropy")
tree_pruned.fit(train_X, train_y)
y_pruned_pred = tree_pruned.predict(test_X)

#from sklearn.metrics import accuracy_score
print("Accuracy on training set:",round(tree_pruned.score(train_X, train_y),3))
print("Accuracy on test set:",accuracy_score(y_pruned_pred, test_y))

# Feature Importance

# Get feature importances from the pruned tree model
feature_importances = tree_pruned.feature_importances_

# Create a DataFrame of feature importances
feature_importance_df = pd.DataFrame({
    'Feature': train_X.columns,
    'Importance': feature_importances
})

# Sort the DataFrame by importance in descending order
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# Display the feature importance DataFrame
print("Feature Importance for the Pruned Decision Tree:")
display(feature_importance_df)

import matplotlib.pyplot as plt

# Group by Class and satisfaction to get counts
satisfaction_by_class = train.groupby(['Class', 'satisfaction']).size().unstack(fill_value=0)

# Calculate percentages for each class
satisfaction_by_class_percent = satisfaction_by_class.apply(lambda x: x / x.sum(), axis=1)

# Plotting pie charts for each class
fig, axes = plt.subplots(1, len(satisfaction_by_class.index), figsize=(18, 6))
axes = axes.flatten()

for i, (flight_class, data) in enumerate(satisfaction_by_class_percent.iterrows()):
    axes[i].pie(data, labels=data.index, autopct='%1.1f%%', startangle=90, colors=['lightcoral', 'lightskyblue'])
    axes[i].set_title(f'Satisfaction in {flight_class} Class')
    axes[i].axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.

plt.tight_layout()
plt.show()

"""### Satisfaction by Customer Type"""

import matplotlib.pyplot as plt

# Group by Customer Type and satisfaction to get counts
satisfaction_by_customer_type = train.groupby(['Customer Type', 'satisfaction']).size().unstack(fill_value=0)

# Calculate percentages for each customer type
satisfaction_by_customer_type_percent = satisfaction_by_customer_type.apply(lambda x: x / x.sum(), axis=1)

# Plotting pie charts for each customer type
fig, axes = plt.subplots(1, len(satisfaction_by_customer_type.index), figsize=(14, 6))
axes = axes.flatten()

for i, (customer_type, data) in enumerate(satisfaction_by_customer_type_percent.iterrows()):
    axes[i].pie(data, labels=data.index, autopct='%1.1f%%', startangle=90, colors=['lightcoral', 'lightskyblue'])
    axes[i].set_title(f'Satisfaction for {customer_type}')
    axes[i].axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Group by Customer Type and satisfaction to get counts
satisfaction_by_customer_type_counts = train.groupby(['Customer Type', 'satisfaction']).size().unstack(fill_value=0)

# Plotting a stacked bar chart
satisfaction_by_customer_type_counts.plot(kind='bar', stacked=True, figsize=(10, 6), color=['lightcoral', 'lightskyblue'])

plt.title('Satisfaction Distribution by Customer Type')
plt.xlabel('Customer Type')
plt.ylabel('Number of Customers')
plt.xticks(rotation=0)
plt.legend(title='Satisfaction')
plt.tight_layout()
plt.show()
